---
name: dynalite

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/dynalite.yml
      - dynalite/**

jobs:
  dynalite:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: dynalite/
          tags: tenzer/dynalite:latest
          platforms: |
            linux/amd64
            linux/arm64
          push: true
