---
name: dynalite

on:
  pull_request:
    paths:
      - .github/workflows/dynalite.yml
      - dynalite/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/dynalite.yml
      - dynalite/**

jobs:
  dynalite:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Test build
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6.10.0
        with:
          context: dynalite/

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6.10.0
        with:
          context: dynalite/
          tags: |
            tenzer/dynalite:latest
            ghcr.io/tenzer/dynalite:latest
            quay.io/tenzerdk/dynalite:latest
          platforms: |
            linux/amd64
            linux/arm64
          push: true
