---
name: fpm

on:
  pull_request:
    paths:
      - .github/workflows/fpm.yml
      - fpm/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/fpm.yml
      - fpm/**

permissions:
  contents: read
  packages: write

jobs:
  fpm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3.2.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Test build fpm:latest
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6.4.1
        with:
          context: fpm/
          target: with-entrypoint

      - name: Build and push fpm:latest
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6.4.1
        with:
          context: fpm/
          target: with-entrypoint
          tags: |
            tenzer/fpm:latest
            ghcr.io/tenzer/fpm:latest
            quay.io/tenzerdk/fpm:latest
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

      - name: Test build fpm:latest
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6.4.1
        with:
          context: fpm/
          target: no-entrypoint

      - name: Build and push fpm:no-entrypoint
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6.4.1
        with:
          context: fpm/
          target: no-entrypoint
          tags: |
            tenzer/fpm:no-entrypoint
            ghcr.io/tenzer/fpm:no-entrypoint
            quay.io/tenzerdk/fpm:no-entrypoint
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
