---
name: fpm

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fpm.yml
      - fpm/**

jobs:
  fpm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push fpm:latest
        uses: docker/build-push-action@v2
        with:
          context: fpm/
          tags: tenzer/fpm:latest
          platforms: linux/amd64  # TODO: Add arm64 support
          push: true
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

      - name: Build and push fpm:no-entrypoint
        uses: docker/build-push-action@v2
        with:
          context: fpm/
          file: fpm/Dockerfile.no-entrypoint
          tags: tenzer/fpm:no-entrypoint
          platforms: linux/amd64  # TODO: Add arm64 support
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
