---
name: uwsgi-werkzeug-echo

on:
  pull_request:
    paths:
      - .github/workflows/uwsgi-werkzeug-echo.yml
      - uwsgi-werkzeug-echo/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/uwsgi-werkzeug-echo.yml
      - uwsgi-werkzeug-echo/**

permissions:
  contents: read
  packages: write

jobs:
  uwsgi-werkzeug-echo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Test build
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6.5.0
        with:
          context: uwsgi-werkzeug-echo/

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6.5.0
        with:
          context: uwsgi-werkzeug-echo/
          tags: |
            tenzer/uwsgi-werkzeug-echo:latest
            ghcr.io/tenzer/uwsgi-werkzeug-echo:latest
            quay.io/tenzerdk/uwsgi-werkzeug-echo:latest
          platforms: |
            linux/amd64
            linux/arm64
          push: true
